// <auto-generated />
namespace Coursework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m18));
        
        string IMigrationMetadata.Id
        {
            get { return "202005261724157_m18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
