// <auto-generated />
namespace Coursework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m114 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m114));
        
        string IMigrationMetadata.Id
        {
            get { return "202005280618545_m114"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
